name: divbox
description: A utility widget for padding and margin.
version: 0.1.1
homepage: https://github.com/vishnumohanrk/divbox

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: